# Generated by Django 4.1 on 2022-09-04 02:12

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_admission_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='unique_id',
            field=models.CharField(default=api.models.generate_random_id, editable=False, max_length=1000, unique=True),
        ),
    ]
