# Generated by Django 4.1 on 2022-09-06 10:54

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_student_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='unique_id',
            field=models.CharField(default=api.models.generate_random_id, editable=False, max_length=600, unique=True),
        ),
    ]
