# Generated by Django 4.1 on 2022-09-06 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sports_attendance_academics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academics',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
        migrations.AlterField(
            model_name='sports',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
    ]
