# Generated by Django 4.1 on 2022-09-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_academics_student_alter_attendance_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academics',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='sports',
            name='Class',
        ),
    ]
