# Generated by Django 4.1 on 2022-09-06 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_academics_class_remove_attendance_class_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Primary_1',
            new_name='Primary1',
        ),
    ]
