# Generated by Django 4.1 on 2022-09-06 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_primary_1_primary1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primary1',
            name='student',
            field=models.ForeignKey(limit_choices_to={'Class': 'Primary 1'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
    ]
