# Generated by Django 4.1 on 2022-09-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_primary1_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_id',
            field=models.IntegerField(max_length=3, null=True),
        ),
    ]
