# Generated by Django 4.1 on 2022-09-06 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_class_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primary1',
            name='student',
            field=models.ForeignKey(limit_choices_to={'Class': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
    ]
