# Generated by Django 4.1 on 2022-09-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_jss1_student_alter_jss2_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jss1',
            name='remark',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jss2',
            name='remark',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jss3',
            name='remark',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='primary1',
            name='remark',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='primary2',
            name='remark',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='primary3',
            name='remark',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='primary4',
            name='remark',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='primary5',
            name='remark',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ss1',
            name='remark',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ss2',
            name='remark',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ss3',
            name='remark',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
